"""Adjusted the id bits to 10

Revision ID: 02fa66ae5662
Revises: 31feb4e5fb4d
Create Date: 2024-12-29 11:32:16.387150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02fa66ae5662'
down_revision = '31feb4e5fb4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplements', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplements', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
