""" parent last name added in immunization

Revision ID: 0b2e38a9a975
Revises: fecdcf134737
Create Date: 2025-01-26 15:00:36.617932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2e38a9a975'
down_revision = 'fecdcf134737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immunization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_last_name', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immunization', schema=None) as batch_op:
        batch_op.drop_column('parent_last_name')

    # ### end Alembic commands ###
