"""create database

Revision ID: 2d4f266c045c
Revises: 
Create Date: 2025-01-25 14:23:04.861520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4f266c045c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_name', sa.String(length=100), nullable=False),
    sa.Column('hospital_address', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mothers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('genotype', sa.String(length=10), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('antenatal_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('blood_pressure', sa.String(length=20), nullable=False),
    sa.Column('tests', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('mother_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['mother_id'], ['mothers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('children',
    sa.Column('children_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('blood_group', sa.String(length=20), nullable=False),
    sa.Column('genotype', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('parent_email', sa.String(length=200), nullable=False),
    sa.Column('nationality', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['mothers.id'], ),
    sa.PrimaryKeyConstraint('children_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mother_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('send_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mother_id'], ['mothers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mother_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mother_id'], ['mothers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('immunization',
    sa.Column('immunization_id', sa.String(), nullable=False),
    sa.Column('children_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('parent_first_name', sa.String(length=200), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('parent_email', sa.String(length=200), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('injections', sa.Text(), nullable=True),
    sa.Column('previous_date', sa.Date(), nullable=False),
    sa.Column('next_date', sa.Date(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['children_id'], ['children.children_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['mothers.id'], ),
    sa.PrimaryKeyConstraint('immunization_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('immunization')
    op.drop_table('supplements')
    op.drop_table('notifications')
    op.drop_table('children')
    op.drop_table('antenatal_records')
    op.drop_table('mothers')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
