"""Added a uuid id

Revision ID: 31feb4e5fb4d
Revises: bb7a85402939
Create Date: 2024-12-29 11:27:31.990478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31feb4e5fb4d'
down_revision = 'bb7a85402939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplements', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplements', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
