""" children table updated

Revision ID: 7374bbb0be4c
Revises: 0b2e38a9a975
Create Date: 2025-01-26 16:14:12.855285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7374bbb0be4c'
down_revision = '0b2e38a9a975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_first_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('parent_last_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_column('parent_last_name')
        batch_op.drop_column('parent_first_name')

    # ### end Alembic commands ###
