"""migrate

Revision ID: f9ee9f387dda
Revises: 
Create Date: 2025-01-24 14:24:41.528332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ee9f387dda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mothers',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('genotype', sa.String(length=10), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('children',
    sa.Column('children_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('blood_group', sa.String(length=20), nullable=False),
    sa.Column('genotype', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('parent_email', sa.String(length=200), nullable=False),
    sa.Column('nationality', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['mothers.id'], ),
    sa.PrimaryKeyConstraint('children_id')
    )
    op.create_table('immunization',
    sa.Column('immunization_id', sa.String(), nullable=False),
    sa.Column('children_id', sa.String(length=200), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('parent_first_name', sa.String(length=200), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('parent_email', sa.String(length=200), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('injections', sa.Text(), nullable=True),
    sa.Column('previous_date', sa.Date(), nullable=False),
    sa.Column('next_date', sa.Date(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['children_id'], ['children.children_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['mothers.id'], ),
    sa.PrimaryKeyConstraint('immunization_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('immunization')
    op.drop_table('children')
    op.drop_table('mothers')
    # ### end Alembic commands ###
