"""migration

Revision ID: fecdcf134737
Revises: 9c1e80203db1
Create Date: 2025-01-26 13:53:43.015870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecdcf134737'
down_revision = '9c1e80203db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_column('genotype')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('parent_email')

    with op.batch_alter_table('immunization', schema=None) as batch_op:
        batch_op.drop_column('parent_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('immunization', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_email', sa.VARCHAR(length=200), nullable=True))

    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_email', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('blood_group', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('genotype', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
